name: Frontend CI/CD

on:
  push:
    branches: [main]
    paths: ['frontend/**']
  pull_request:
    branches: [main]
    paths: ['frontend/**']
  workflow_dispatch:

permissions:
  security-events: write

jobs:
  deploy:
    uses: ./.github/workflows/service-ci-cd.yml
    with:
      service: "frontend"
      language: "node"
      port: 80
      ingress: "external"
    secrets: inherit
