name: Notification CI/CD

on:
  push:
    branches: [main]
    paths: ['notification-service/**']
  pull_request:
    branches: [main]
    paths: ['notification-service/**']
  workflow_dispatch:

permissions:
  security-events: write

jobs:
  deploy:
    uses: ./.github/workflows/service-ci-cd.yml
    with:
      service: "notification-service"
      language: "node"
      port: 3002
      ingress: "internal"
    secrets: inherit
