name: Order CI/CD

on:
  push:
    branches: [main]
    paths: ['order-service/**']
  pull_request:
    branches: [main]
    paths: ['order-service/**']
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/service-ci-cd.yml
    with:
      service: "order-service"
      language: "node"
      port: 3001
      ingress: "internal"
    secrets: inherit
